Mailjet integration
CloudStuffTech/go-utils pull request #1
Opened 2021-04-09 09:37 UTC by irohit427

2021-04-11 06:22 UTC, Hemant-Mann requested changes

2021-04-11 06:22 UTC, Hemant-Mann commented on mail/mail.go
> +	mailjet "github.com/mailjet/mailjet-apiv3-go"
add this in the readme file @irohit427

2021-04-11 06:22 UTC, Hemant-Mann commented on mail/mail.go
> +		log.Fatal(err)
you can not log error inside a function, you need to return it

2021-04-11 06:22 UTC, Hemant-Mann commented on mail/mail.go
> +	TextPart, HtmlPart string
there should be option to add CC (Ref: line 23) and Reply To

2021-04-13 12:30 UTC, Hemant-Mann requested changes
ReplyTo is still not added

2021-04-13 13:03 UTC, irohit427 commented
> ReplyTo is still not added

Added ReplyTo

2021-04-14 05:36 UTC, Hemant-Mann requested changes

2021-04-14 05:36 UTC, Hemant-Mann commented on mail/mail.go
> +		  }
```suggestion
		  },
```

2021-04-14 07:28 UTC, irohit427 commented on mail/mail.go
> +		  }
resolved

2021-04-14 07:36 UTC, Hemant-Mann commented on mail/mail.go
> +		  HTMLPart: params.HTMLPart
```suggestion
		  HTMLPart: params.HTMLPart,
```

2021-04-14 07:36 UTC, Hemant-Mann approved these changes

2021-04-14 07:37 UTC, merged